Oxide = {
  length = 1e-08
  relative_permitivity = 3.9
  v_top = 1.0
  v_bottom = 0.0
  traps = {
  locations = [0.01, 0.1, 0.5, 0.61, 0.71]
  occ_probs = [0.1, 0.1, 0.1, 0.1, 0.1]}
  transport = {
  mobility = 1.0
  m_eff = 1.0
  nu_0 = 1.0
  relaxation_distance = 1.0}}